apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: storefront-permissions
  annotations:
    github.com/project-slug: vtex-apps/storefront-permissions
spec:
  system: b2b-suite
  type: backend-api
  lifecycle: maintenance
  owner: b-2-b-enabler
